# Generated by Django 3.0.3 on 2020-11-10 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nearby',
            old_name='adress',
            new_name='address',
        ),
    ]
